### ISSUE TITLE
Comparison with msgbus

### ISSUE THREAD

**Issue by anderspitman** [patchbay-pub/patchbay-simple-server#2]
[msgbus](https://github.com/prologic/msgbus) might serve as a nice self-hostable alternative to
patchbay.

**Comment by prologic** [comment]
I'mm come up with some "poor man'x X" in msgbus and  do a feature comparision and see where we lie

**Comment by anderspitman** [comment]
Thanks! Don't spend too much time on it. Mostly I just wanted to get a feel for how it compares on simplicity, which is the main selling point of patchbay.

**Comment by prologic** [comment]
Immediately I can see some differences between patchbay and msgbus that don't quite make using msgbus for the same things quite suitable.

- msgbus lacks a "blocking mode" fir simple curl / GET requests
   - But does have a websocket subscribe model for real-time pub/sub
- msgbus packages the payload into a JSON structure
  - This makes doing simple curl things a bit more involved

Running the server:

```#!sh
$ git clone https://github.com/prologic/msgbus.git
$ cd msgbus
$ make
INFO[0000] msgbusd 0.1.1-dev@b78e2d9 listening on :8000
```

Making a `curl` request:

```#!sh
$ curl -q -s http://localhost:8000/foo
no messages enqueued for topic: foo
```

Notice how it doesn't block? This makes it less useful compared to patchbay; but could be improved with a `?block=1` as an optional parameter or change the default behaviour.

Generally with msgbus you would "subscribe" to a topic with the `msgbus` CLI:

```#!sh
$ ./cmd/msgbus/msgbus -u http://localhost:9000/ sub foo cat
INFO[0000] successfully connected to ws://localhost:9000/foo
```

This lets you execute the `<command>` (`cat` in this example) on receipt of a payload on that topic:

Posting a message:

```#!sh
$ echo 'hello' | curl -q -s -X POST -d @- http://localhost:9000/foo
```

And the subscribed `cat` above would show:

```#!sh
$ ./cmd/msgbus/msgbus -u http://localhost:9000/ sub foo cat
INFO[0000] successfully connected to ws://localhost:9000/foo
{"id":0,"topic":{"name":"foo","seq":1,"created":"2019-11-28T10:24:10.519824+10:00"},"payload":"aGVsbG8=","created":"2019-11-28T10:26:23.060627+10:00"}
```

You can see many examples of this model in:

- [ircnotify](https://github.com/prologic/dockerfiles/blob/master/ircnotify/start.sh)
- [alert](https://github.com/prologic/dockerfiles/blob/master/alert/start.sh)
- [autoupdate](https://github.com/prologic/dockerfiles/blob/master/autoupdate/start.sh)

As some real-world examples.

This is basically how I do CD (Continuous Delivery_) via `autoupdate` to Docker Swarm clusters running services.

This is also how I send Prometheus/AlertManager alerts out via IRC via `alert`.

And how I send general-purpose IRC notifications via `ircnotify`

**Comment by prologic** [comment]
I am of course open to suggestions and ideas to making msgbus a suitable self-hsoted alternative patchbay prologic/msgbus#14

**Comment by anderspitman** [comment]
@prologic sorry for the delay. I think patchbay and msgbus are very much created in the same spirit. Though it seems like msgbus is definitely more advanced, while patchbay is focused on simplicity at all costs (ie if a feature would add much complexity, the answer is probably to use a different tool, such as msgbus maybe). The only tricky thing I see with using a subset of msgbus as a stand-in for patchbay is the requirement to use the msgbus client in order to subscribe. I think being able to use curl on both ends is valuable.

**Comment by prologic** [comment]
No apologies necessary! This is probably as lo-pri as it geos :) As I said I filed an issue to possibly make msgbus more generally useful from `curl` and in-line with patchbay in prologic/msgbus#14; So we can move the discussion there if you like and close this. The only way I can think of to do this is to either:

- Add `User-Agent` (typical RESTful style) `User-Agent` conditional behaviour

or:

- Optional URL parameters that explicitly control behaviour.

**Comment by anderspitman** [comment]
I guess that probably makes more sense.
