### ISSUE TITLE
site down?

### ISSUE THREAD

**Issue by jedahan** [patchbay-pub/patchbay-simple-server#5]
There is a redirect from port 80 to 443, but that looks like its down...

![Screenshot 2023-12-12 at 1 43 27 PM](https://github.com/patchbay-pub/patchbay-simple-server/assets/32407/4144df7b-8b67-4b0a-b534-62a91776d460)

![Screenshot 2023-12-12 at 1 43 46 PM](https://github.com/patchbay-pub/patchbay-simple-server/assets/32407/42d575cf-f44a-4edb-b388-556f99ff3424)

**Comment by anderspitman** [comment]
Thanks @jedahan. It's back up
